apiVersion: v1
kind: Service
metadata:
  name: {{ include "activetigger.apiServiceName" . }}
  labels:
    {{- include "activetigger.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "activetigger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
