{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activetigger.secretName" . }}
  labels:
    {{- include "activetigger.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-password: {{ .Values.secrets.rootPassword | quote }}
  secret-key: {{ .Values.secrets.secretKey | quote }}
  postgresql-password: {{ .Values.secrets.postgresqlPassword | quote }}
  {{- if .Values.postgresql.enabled }}
  database-url: {{ include "activetigger.databaseUrl" . | quote }}
  {{- end }}
{{- end }}
